name: Unzip File in Repository

on:
  workflow_dispatch: # Allows you to manually run the workflow
  push: # Runs automatically when you push changes to the repository
    branches:
      - main # Replace 'main' with your branch name if different

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Pulls the repository into the virtual machine

      - name: Unzip Lakshmi.zip
        run: |
          unzip Lakshmi.zip -d Lakshmi # Extracts the zip file into a folder named 'Lakshmi'
          ls -l # Lists the unzipped files for confirmation

      - name: Commit and Push Unzipped Files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub-provided token for authentication
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Lakshmi
          git commit -m "Unzipped Lakshmi.zip"
          git push origin main # Pushes to the main branch
